"""Replaces the hand-typed Cisco CLI strings in cells across 'VLAN Config
(9300)' / 'VLAN Config (2960)' (e.g. that sheet's literal `Commands`
column) with a generated export from the same relational port data the UI
edits -- so the two can't drift the way a typed-once cell can.

Interface naming isn't guessed: the real Drop List As-Built sheet's own
formulas reference actual IOS interface abbreviations for this deployment
("Twe1/0/1" = TwentyFiveGigE, "Te1/0/1" = TenGigE), which is why
`interface_prefix` is a parameter here rather than a hardcoded
"GigabitEthernet1/0/" -- the right prefix depends on the physical switch's
port speed, which this module has no way to know on its own.

Meraki MS-series switches (the 'MS390 provisioning sheet') aren't
configured via IOS-style CLI at all -- Meraki is dashboard/API driven --
so exporting fake CLI for them would be actively misleading. They get a
structured port list shaped like the Meraki API's port-update body
instead.
"""

import json
import re
from dataclasses import dataclass

DEFAULT_INTERFACE_PREFIX = "GigabitEthernet1/0/"

# Meraki MS-series model numbers always start with "MS" followed by
# digits (MS120, MS225, MS390, ...) -- a plain "ms" substring check would
# false-positive on plenty of unrelated model strings.
_MERAKI_MODEL_RE = re.compile(r"\bMS\d")


def _is_meraki(switch_model: str) -> bool:
    return bool(_MERAKI_MODEL_RE.search(switch_model.upper())) or "meraki" in switch_model.lower()


@dataclass
class SwitchPortConfig:
    port_number: int
    mode: str  # "access" | "trunk"
    vlan_number: int | None
    description: str | None


def generate_ios_config(
    switch_model: str, ports: list[SwitchPortConfig], interface_prefix: str = DEFAULT_INTERFACE_PREFIX
) -> str:
    lines = [
        f"! {switch_model} port configuration",
        "! Generated by Network Design Platform -- verify before applying",
        "!",
    ]
    for port in sorted(ports, key=lambda p: p.port_number):
        lines.append(f"interface {interface_prefix}{port.port_number}")
        if port.description:
            lines.append(f" description {port.description}")
        if port.mode == "trunk":
            lines.append(" switchport mode trunk")
        else:
            lines.append(" switchport mode access")
            if port.vlan_number is not None:
                lines.append(f" switchport access vlan {port.vlan_number}")
        lines.append("!")
    return "\n".join(lines) + "\n"


def generate_meraki_port_list(ports: list[SwitchPortConfig]) -> list[dict]:
    """Shaped like the body of Meraki's 'Update a switch port' API call,
    so this can be scripted against the API directly or pasted into the
    dashboard's bulk port editor."""
    return [
        {
            "portId": str(port.port_number),
            "name": port.description,
            "type": "trunk" if port.mode == "trunk" else "access",
            "vlan": port.vlan_number,
        }
        for port in sorted(ports, key=lambda p: p.port_number)
    ]


def export_switch_config(
    switch_model: str, ports: list[SwitchPortConfig], interface_prefix: str = DEFAULT_INTERFACE_PREFIX
) -> tuple[str, str]:
    """Returns (content, content_type), picking the export format for the
    switch model family. Meraki MS-series get JSON; everything else
    (assumed IOS-capable -- 9300/2960 and similar) gets CLI text."""
    if _is_meraki(switch_model):
        return json.dumps(generate_meraki_port_list(ports), indent=2) + "\n", "application/json"
    return generate_ios_config(switch_model, ports, interface_prefix), "text/plain"
